"""Canonical model templates independent of environment state."""

from __future__ import annotations


MODEL_TEMPLATES: list[dict] = [
    {
        "id": "moonshotai/kimi-k2.5",
        "label": "Kimi K2.5",
        "default": False,
        "provider": "nvidia",
        "upstream_model": "moonshotai/kimi-k2.5",
        "protocol": "nvidia_chat_completions",
        "capabilities": {"thinking": True, "media": True, "agent": False},
        "params": {
            "temperature_thinking": 1.0,
            "temperature_standard": 0.6,
            "top_p": 1.0,
            "thinking_control": "call_time",
            "thinking_kwarg_key": "chat_template_kwargs",
            "thinking_kwarg_field": "thinking",
        },
        "context_window": 131072,
    },
    {
        "id": "qwen/qwen3.5-397b-a17b",
        "label": "Qwen 3.5",
        "default": False,
        "provider": "nvidia",
        "upstream_model": "qwen/qwen3.5-397b-a17b",
        "protocol": "nvidia_chat_completions",
        "capabilities": {"thinking": True, "media": False, "agent": True},
        "params": {
            "temperature_thinking": 0.6,
            "temperature_standard": 0.6,
            "top_p": 0.95,
            "thinking_control": "call_time",
            "thinking_kwarg_key": "chat_template_kwargs",
            "thinking_kwarg_field": "enable_thinking",
        },
        "context_window": 128000,
        "agent_config": {
            "max_steps": 8,
            "tools": ["web_search", "read_url", "python_exec"],
            "enable_planning": True,
            "enable_reflection": True,
        },
    },
    {
        "id": "z-ai/glm5",
        "label": "GLM 5",
        "default": False,
        "provider": "nvidia",
        "upstream_model": "z-ai/glm5",
        "protocol": "nvidia_chat_completions",
        "capabilities": {"thinking": True, "media": False, "agent": True},
        "params": {
            "temperature_thinking": 0.7,
            "temperature_standard": 0.7,
            "top_p": 1.0,
            "thinking_control": "construct_time",
            "thinking_kwarg_key": "extra_body",
            "thinking_kwarg_field": "chat_template_kwargs",
        },
        "context_window": 128000,
        "agent_config": {
            "max_steps": 8,
            "tools": ["web_search", "read_url", "python_exec"],
            "enable_planning": True,
            "enable_reflection": True,
        },
    },
    {
        "id": "anthropic/claude-sonnet-4-6",
        "label": "Claude Sonnet 4.6",
        "default": False,
        "provider": "anthropic",
        "upstream_model": "claude-sonnet-4-6",
        "protocol": "anthropic_messages",
        "capabilities": {"thinking": True, "media": False, "agent": True},
        "params": {
            "temperature_thinking": 0.7,
            "temperature_standard": 0.6,
            "top_p": 1.0,
            "thinking_control": "none",
        },
        "context_window": 200000,
        "agent_config": {
            "max_steps": 8,
            "tools": ["web_search", "read_url", "python_exec"],
            "enable_planning": True,
            "enable_reflection": True,
        },
    },
    {
        "id": "openai/gpt-5.3-codex",
        "label": "GPT-5.3 Codex",
        "default": True,
        "provider": "openai",
        "upstream_model": "gpt-5.3-codex",
        "protocol": "openai_responses",
        "capabilities": {"thinking": True, "media": False, "agent": True},
        "params": {
            "temperature_thinking": 0.7,
            "temperature_standard": 0.6,
            "top_p": 1.0,
            "thinking_control": "none",
        },
        "context_window": 200000,
        "agent_config": {
            "max_steps": 8,
            "tools": ["web_search", "read_url", "python_exec"],
            "enable_planning": True,
            "enable_reflection": True,
        },
    },
    {
        "id": "google/gemini-3-pro-preview",
        "label": "Gemini 3 Pro Preview",
        "default": False,
        "provider": "google",
        "upstream_model": "gemini-3-pro-preview",
        "protocol": "google_generate_content",
        "capabilities": {"thinking": True, "media": False, "agent": True},
        "params": {
            "temperature_thinking": 0.7,
            "temperature_standard": 0.6,
            "top_p": 1.0,
            "thinking_control": "none",
        },
        "context_window": 1048576,
        "agent_config": {
            "max_steps": 8,
            "tools": ["web_search", "read_url", "python_exec"],
            "enable_planning": True,
            "enable_reflection": True,
        },
    },
]

TEMPLATE_INDEX: dict[str, dict] = {model["id"]: model for model in MODEL_TEMPLATES}
